### ISSUE TITLE
When I create a new post it does not order the posts by date

### ISSUE THREAD

**Issue by bitmanuc** [podcastjs/podcastjs#24]
When I create a new post it does not order the posts by date

The oldest post stays at the top

![image_2024-07-07_112330986](https://github.com/podcastjs/podcastjs/assets/31716953/f956d361-220f-496c-8307-c2c3046ff933)

**Comment by jrichardsz** [comment]
Fixed.

Just don't forget to use quotes in the datetime field

```
layout : post
title : Contributing
description : To contribute, follow the nex steps
category : ai
tags : series, fiction
comments : true 
author : Rich Dotcom
thumbnail_image_url: images/img_3.jpg
datetime : "2017-08-20"
duration: 0:30:20
sound:
  type : simple_url
  value : http://www.largesound.com/ashborytour/sound/AshboryBYU.mp3
  language: en
```

The problem was that js-yaml parser y default parse the string to date but the framework needs a string

**Comment by jrichardsz** [comment]
Fixed
